### PR TITLE
Add missing name property to Checker

### PR DESCRIPTION
**Pull request by szepeviktor**
props. @phpstan 👀

### CODE REVIEW

**Comment by szepeviktor** [comment]
:bulb: BTW It is easy to start with static analysis.

```
composer require --dev szepeviktor/phpstan-wordpress
vendor/bin/phpstan analyse -c vendor/szepeviktor/phpstan-wordpress/extension.neon -l 5 src/
```

**Comment by szepeviktor** [comment]
Thank you.

1 PR left :)

**Comment by jakubmikita** [comment]
Yes, I'm looking into it, thanks! :) 

One question - why PHPStan, not Psalm ie? Are there any pros or cons?

**Comment by szepeviktor** [comment]
Please see https://github.com/coenjacobs/mozart/pull/110#issuecomment-761871071

**Pull request merged**
